const { User } = require('../models/index');
const { hashPassword, comparePassword } = require('../utils/bcrypt.util');
const { signToken } = require('../utils/jwt.util');
const { AppError } = require('../middlewares/errorHandler.middleware');

/**
 * Register a new user or seller
 * @param {object} data - { name, email, password, role, phone }
 * @returns {{ user, token }}
 */
const register = async (data) => {
  const { name, email, password, role = 'user', phone } = data;

  // Check if email already exists
  const existingUser = await User.findOne({ where: { email } });
  if (existingUser) {
    throw new AppError('Email is already registered', 409);
  }

  // Hash password before storing
  const password_hash = await hashPassword(password);

  // Create user — slug is auto-generated by beforeCreate hook
  const user = await User.create({
    name,
    email,
    password_hash,
    role,
    phone: phone || null,
  });

  // Sign JWT with essential payload only
  const token = signToken({
    id: user.id,
    email: user.email,
    role: user.role,
  });

  // Return user without password_hash (defaultScope excludes it)
  const safeUser = await User.findByPk(user.id);

  return { user: safeUser, token };
};

/**
 * Login with email and password
 * @param {string} email
 * @param {string} password
 * @returns {{ user, token }}
 */
const login = async (email, password) => {
  // Use unscoped() to include password_hash for comparison
  const user = await User.unscoped().findOne({
    where: { email },
  });

  if (!user) {
    throw new AppError('Invalid email or password', 401);
  }

  if (!user.is_active) {
    throw new AppError(
      'Your account has been deactivated — contact support',
      403
    );
  }

  const isPasswordValid = await comparePassword(password, user.password_hash);

  if (!isPasswordValid) {
    throw new AppError('Invalid email or password', 401);
  }

  const token = signToken({
    id: user.id,
    email: user.email,
    role: user.role,
  });

  // Return user without password_hash
  const safeUser = await User.findByPk(user.id);

  return { user: safeUser, token };
};

/**
 * Get current logged-in user by ID
 * @param {string} userId
 * @returns {User}
 */
const getMe = async (userId) => {
  const user = await User.findByPk(userId);

  if (!user) {
    throw new AppError('User not found', 404);
  }

  return user;
};

class AuthService {
  constructor() {
    this.register = register;
    this.login = login;
    this.getMe = getMe;
  }
}

module.exports = new AuthService();